version: '3.7'
services:
  db:
    image: postgres:15
    container_name: arman_postgres
    restart: always
    environment:
      POSTGRES_USER: arman
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5555:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: arman_api
    depends_on:
      - db
    ports:
      - "8080:8000"
    environment:
      DATABASE_URL: postgresql://arman:password@db:5432/db
    volumes:
      - ./src:/app

volumes:
  postgres_data: